version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            go get -u golang.org/x/lint/golint
            go mod download
      - run:
          name: Perform styling checks
          command: |
            golint ./...
            go vet ./...
      - run:
          name: Run tests
          command:  go test -v ./...