version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run: go mod download
      - run: go vet ./...
      - run: go lint ./...
      - run: go test -v ./...